#!/usr/bin/env bash
# Emit a translucent version of the current pywal background for rofi.
#
# pywal's own colors-rofi-dark.rasi only carries opaque colours, and rasi has
# no way to add alpha to an imported colour — so the panel can never be glassy
# from that file alone. This writes one extra variable that pastel.rasi imports.
#
# Output: ~/.cache/wal/colors-rofi-alpha.rasi

set -e
OUT="$HOME/.cache/wal/colors-rofi-alpha.rasi"
[ -f "$HOME/.cache/wal/colors.json" ] || exit 0

python3 - "$OUT" <<'PY'
import json, sys, os

out = sys.argv[1]
wal = json.load(open(os.path.expanduser("~/.cache/wal/colors.json")))
bg = wal["special"]["background"].lstrip("#")

# D9 ~= 85% opaque: enough body to read against a busy wallpaper while still
# letting the compositor blur read through as glass.
open(out, "w").write(
    "/* generated by ~/.config/waypaper/wal-rofi.sh */\n"
    "* {\n"
    f"    bg-trans:  #{bg}D9;\n"
    f"    field-bg:  #{bg}66;\n"
    "}\n"
)
PY
exit 0
