#!/bin/bash
# source "$HOME/.config/colors.sh"

# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m config external_bar all:$(sketchybar --query bar | jq .height):0
# yabai -m config menubar_opacity 0.0

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 2
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 7

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt

# set modifier + left-click drag to move window
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# when window is dropped in center of another window, swap them (on edges it will split it)

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 0.5
yabai -m config normal_window_opacity 0.6

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Warp|Ghostty|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$"  manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add app="^Pycharm" manage=off
yabai -m rule --add app="^orbStack" manage=off
yabai -m rule --add app="^OpenVPN Connect" manage=off
yabai -m config mouse_drop_action swap

yabai -m rule --add app="^Google Chat$" space=^1
# yabai -m rule --add app="^Microsoft Teams (work or school)$" space=^1
# yabai -m rule --add app="^Visual Studio Code - Insiders$" space=1
# yabai -m rule --add app="^Warp$" space=2

yabai -m rule --add app="^SigmaOS$" space=3
yabai -m rule --add app="^Google Chrome$" space=1
yabai -m rule --add app="^Notion Calendar$" space=5
yabai -m rule --add app="Cursor" opacity=0.83
yabai -m rule --add app="Code - Insiders" opacity=0.83
yabai -m rule --add app="Finder" opacity=0.83
