
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- hl.config({ autogenerated = true }) -- remove this line to remove the warning

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

-- Laptop panel, anchored at origin
hl.monitor({
    output   = "eDP-1",
    mode     = "preferred",   -- 1920x1080@60
    position = "0x0",
    scale    = 1,
})

-- Xiaomi ultrawide, to the right of the laptop.
-- Its EDID marks 3440x1440@30 as "preferred", which made everything feel
-- sluggish — pin 50Hz, the max this link offers at native res. (The panel
-- itself can do 100Hz+; getting there needs a higher-bandwidth cable/port.)
-- Matched by desc: so the rule survives moving to a different port/dock.
hl.monitor({
    output   = "desc:Xiaomi Corporation Mi monitor 5506010002216",
    mode     = "3440x1440@50",
    position = "1920x0",
    scale    = 1,
})

-- Acer X127H projector over HDMI — mirror the laptop panel.
-- Its EDID prefers 1024x768; pin 1080p to match eDP-1 so the mirror is 1:1.
-- Matched by desc: so extending stays the default for other HDMI displays.
hl.monitor({
    output = "desc:Acer Technologies Acer X127H JP3110015900",
    mode   = "1920x1080@60",
    scale  = 1,
    mirror = "eDP-1",
})

-- Fallback for anything else that gets plugged in
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "ghostty"
local fileManager = "ranger"
-- rofi: themed from pywal via ~/.config/rofi/pastel.rasi, so it recolours with
-- the wallpaper. To go back to hyprlauncher, set this to "hyprlauncher" and
-- restore the " -t" toggle on the SUPER+R bind below.
local menu        = "rofi -show drun"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
  -- nm-applet removed: duplicated waybar's network module. Also masked in
  -- ~/.config/autostart/nm-applet.desktop, since uwsm starts XDG autostart
  -- entries and /etc/xdg/autostart/nm-applet.desktop would revive it.
  hl.exec_cmd("syncthing")
  -- Syncthing tray icon. Must be launched with the SYSTEM python: the script's
  -- shebang is "#!/usr/bin/env python3", which resolves to miniconda's
  -- interpreter here, and that has no PyGObject ("No module named 'gi'") — so
  -- plain `syncthing-gtk` silently dies on startup.
  -- Its config is set to autostart_daemon=0 / autokill_daemon=0 so it attaches
  -- to the daemon started above instead of spawning a second one (and killing
  -- the real one when the GUI exits).
  hl.exec_cmd("/usr/bin/python3 /usr/bin/syncthing-gtk --minimized")
  hl.exec_cmd("trayscale")
  -- GTK_THEME is a no-op here: cursor-clip is GTK4/libadwaita and GTK4
  -- dropped the old theme system. Its opacity comes from window_bg_color in
  -- ~/.config/gtk-4.0/gtk.css (pywal-generated), plus a blur layer rule.
  hl.exec_cmd("cursor-clip --daemon")
  hl.exec_cmd("swaync")                -- notification daemon, must be up before waybar's module subscribes
  hl.exec_cmd("waybar")
  hl.exec_cmd("awww-daemon")           -- wallpaper daemon (waypaper's backend)
  hl.exec_cmd("waypaper --restore")    -- reapply last wallpaper silently (no GUI)
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("hypridle")              -- auto-lock (10 min) + screen off (10.5 min)
  hl.exec_cmd("hyprlauncher -d --quiet") -- launcher daemon: instant opens
  -- Load hy3 (built manually against system headers; see memory note)
  hl.exec_cmd("hyprctl plugin load /home/oluwaseyi/.local/share/hy3/libhy3.so")
  hl.exec_cmd("hyprpm reload -n")      -- hyprpm-managed plugins (hyprglass)

end)

-- awww caches wallpapers per-output, so a monitor plugged in after startup
-- sits on a black fill — reapply the saved wallpaper whenever one appears.
hl.on("monitor.added", function ()
  hl.exec_cmd("waypaper --restore")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

hl.config({
  ecosystem = {
    enforce_permissions = true,
  },
})

hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")
hl.permission("/home/oluwaseyi/.local/share/hy3/libhy3.so", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 3,
        gaps_out = 3,

        border_size = 0,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        -- hy3 (i3-like manual tiling) when the plugin is loaded, dwindle otherwise
        layout = (hl.plugin ~= nil and hl.plugin.hy3 ~= nil) and "hy3" or "dwindle",
    },

    decoration = {
        rounding       = 15,
        rounding_power = 2,

        -- Focused window is ink-solid for readability (macOS-style);
        -- unfocused windows keep a hint of glass
        active_opacity   = 1.0,
        inactive_opacity = 0.85,

        -- Mild saturation boost to fake back some P3 punch on these
        -- narrow-gamut panels (see shaders/vibrance.glsl)
        screen_shader = "/home/oluwaseyi/.config/hypr/shaders/vibrance.glsl",

        shadow = {
            enabled      = false,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 4,
            passes    = 2,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
    gestures = {
        workspace_swipe_invert = false,
        workspace_swipe_min_speed_to_force = 2,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

-- Snappy profile: windows open/close instantly, everything else is a short,
-- quick transition (speed is in 100ms units — 1 = 100ms).
-- SUPER+F1 game mode still kills animations entirely.
hl.animation({ leaf = "global",        enabled = true,  speed = 2,    bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 2,    bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 1.5,  bezier = "quick" })
hl.animation({ leaf = "windowsIn",     enabled = false })  -- instant open
hl.animation({ leaf = "windowsOut",    enabled = false })  -- instant close
hl.animation({ leaf = "fadeIn",        enabled = false })
hl.animation({ leaf = "fadeOut",       enabled = false })
hl.animation({ leaf = "fade",          enabled = true,  speed = 1,    bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 1.5,  bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 1.5,  bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1,    bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1,    bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1,    bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.2,  bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1,    bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.2,  bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 3,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = true, -- If true disables the random hyprland logo / anime girl background. :(
        focus_on_activate      = true,  -- If true, windows will be focused when they are activated. If false, they will not be focused.
        font_family             = "Fantasque Sans Mono", -- The font family to use for window titles and other text. You can use any font installed on your system.

    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        -- macOS-like pointer feel: adaptive accel + a real speed bump.
        -- 0 (stock libinput) needed several wrist strokes to cross the
        -- 1920+3440px span. Range -1.0..1.0; raise/lower to taste.
        sensitivity   = 0.2,
        accel_profile = "adaptive",

        touchpad = {
            natural_scroll = false,
            clickfinger_behavior = true, -- mac-style: 2-finger tap = right click, 3 = middle
        },
    },
})

hl.gesture({
    fingers = 4,
    direction = "horizontal",
    action = "workspace"
})

-- Per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more

-- Built-in Synaptics trackpad: extra speed on top of the global bump —
-- Mac trackpads run hotter than mice, this mirrors that feel
hl.device({
    name        = "syna30b3:00-06cb:ce08",
    sensitivity = 0.4,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + Q", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(terminal .. " -e " .. fileManager))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("loginctl lock-session"))  -- lock screen (hyprlock via hypridle)
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
-- Project picker rather than a bare window: rofi list -> `code <path>`,
-- so there is no File>Open Folder step. Not the Project Manager
-- extension's own picker — its commands need an existing VS Code
-- window and its store is empty; this reads VS Code's own recents.
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/code-picker.sh"))
-- Quake-style drop-down terminal living in the scratchpad: first press
-- spawns it, later presses toggle visibility so the shell persists.
hl.bind(mainMod .. " + grave", hl.dsp.exec_cmd("$HOME/.config/waybar/scripts/scratch-term.sh"))
-- One-line learning capture -> the Syncthing-backed pool at
-- ~/ALIAS/learning (INBOX.md + daily/). Deliberately not inside a code
-- project: APF-C3/Notes is a Python package, not a note store.
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("$HOME/.config/waybar/scripts/learn-capture.sh"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())

if hl.plugin ~= nil and hl.plugin.hy3 ~= nil then
    ----------------------------------------------------
    -- hy3: i3-like manual tiling binds
    ----------------------------------------------------
    local hy3 = hl.plugin.hy3

    -- Move focus with mainMod + arrow keys (tree-aware)
    hl.bind(mainMod .. " + left",  hy3.move_focus("l"))
    hl.bind(mainMod .. " + right", hy3.move_focus("r"))
    hl.bind(mainMod .. " + up",    hy3.move_focus("u"))
    hl.bind(mainMod .. " + down",  hy3.move_focus("d"))

    -- Move windows with mainMod + SHIFT + arrow keys
    hl.bind(mainMod .. " + SHIFT + left",  hy3.move_window("l"))
    hl.bind(mainMod .. " + SHIFT + right", hy3.move_window("r"))
    hl.bind(mainMod .. " + SHIFT + up",    hy3.move_window("u"))
    hl.bind(mainMod .. " + SHIFT + down",  hy3.move_window("d"))

    -- i3-style splits: pick where the next window opens
    hl.bind(mainMod .. " + H", hy3.make_group("h", { ephemeral = true }))   -- split horizontal
    hl.bind(mainMod .. " + B", hy3.make_group("v", { ephemeral = true }))   -- split vertical ("below")
    hl.bind(mainMod .. " + W", hy3.make_group("tab", { toggle = true }))    -- i3 tabbed container
    hl.bind(mainMod .. " + J", hy3.change_group("opposite"))                -- flip split direction

    -- Focus parent / child container (i3's "focus parent")
    hl.bind(mainMod .. " + A",         hy3.change_focus("raise"))
    hl.bind(mainMod .. " + SHIFT + A", hy3.change_focus("lower"))

    -- Cycle tabs in a tabbed group
    hl.bind(mainMod .. " + bracketleft",  hy3.focus_tab({ direction = "l", wrap = true }))
    hl.bind(mainMod .. " + bracketright", hy3.focus_tab({ direction = "r", wrap = true }))

    -- Kill the whole selected node (window or entire group)
    hl.bind(mainMod .. " + SHIFT + Q", hy3.kill_active())
else
    ----------------------------------------------------
    -- Fallback: stock dwindle binds (hy3 not loaded)
    ----------------------------------------------------
    hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

    -- Move focus with mainMod + arrow keys
    hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
    hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
    hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
    hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

    -- Move windows with mainMod + SHIFT + arrow keys
    hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
    hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
    hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
    hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))
end

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i, follow = false }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Screenshots (grimblast; --freeze stills the screen while you select)
hl.bind("SUPER + Print",         hl.dsp.exec_cmd('grimblast --freeze copy area'))                    -- region/window → clipboard
hl.bind("Print",                 hl.dsp.exec_cmd('grimblast copy output'))                           -- full screen → clipboard
hl.bind("SUPER + SHIFT + Print", hl.dsp.exec_cmd('grimblast --freeze save area - | swappy -f -'))    -- region → annotate → save/copy
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd('cursor-clip'))

-- Screen recording (wl-screenrec, VAAPI; script toggles start/stop)
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("~/.config/hypr/scripts/record.sh"))          -- region
hl.bind(mainMod .. " + CTRL + R",  hl.dsp.exec_cmd("~/.config/hypr/scripts/record.sh output"))   -- focused monitor




--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- ── HyprGlass — Liquid Glass on shell surfaces ───────────────
if hl.plugin ~= nil and hl.plugin.hyprglass ~= nil then
    local hg = hl.plugin.hyprglass

    hg.config({
        default_theme = "dark",
        layers = { enabled = true },
    })

    -- whitelist: only these layers get glassed (the wallpaper layer stays untouched)
    hg.layer("waybar",       { preset = "subtle", mask_threshold = 0.05 })
    hg.layer("swaync-control-center",      { mask_threshold = 0.05 })
    hg.layer("swaync-notification-window", { mask_threshold = 0.05 })
    hg.layer("hyprlauncher", { preset = "subtle" })
    hg.layer("rofi",         { preset = "subtle" })

    -- keep video and fullscreen windows clean
    hl.window_rule({ name = "hyprglass-off-media",      match = { class = "^(mpv|vlc)$" }, tag = "+hyprglass_disabled" })
    hl.window_rule({ name = "hyprglass-off-fullscreen", match = { fullscreen = true },     tag = "+hyprglass_disabled" })
else
    -- fallback: plain frosted blur when hyprglass isn't loaded
    hl.layer_rule({ match = { namespace = "^hyprlauncher$" }, blur = true, ignore_alpha = 0.2 })
    hl.layer_rule({ match = { namespace = "^rofi$" },         blur = true, ignore_alpha = 0.2 })
    hl.layer_rule({ match = { namespace = "^waybar$" },       blur = true, ignore_alpha = 0.2 })
    -- swaync was missing here, so notification cards rendered flat against
    -- whatever was behind them instead of frosted like everything else.
    hl.layer_rule({ match = { namespace = "^swaync-notification-window$" }, blur = true, ignore_alpha = 0.2 })
    hl.layer_rule({ match = { namespace = "^swaync-control-center$" },      blur = true, ignore_alpha = 0.2 })
    -- cursor-clip's overlay is translucent by design and had no blur, so the
    -- wallpaper showed through raw and the entries were unreadable. Note the
    -- anchored "$": cursor-clip ALSO puts up a fullscreen "cursor-clip-capture"
    -- input layer, and blurring that would blur the entire screen.
    hl.layer_rule({ match = { namespace = "^cursor-clip$" }, blur = true, ignore_alpha = 0.0 })
end

-- Ghostty handles its own glass (background-opacity in its config) with
-- text staying solid — keep the compositor from fading it on top of that.
hl.window_rule({
    name  = "ghostty-solid-text",
    match = { class = "^(com\\.mitchellh\\.ghostty|ghostty)$" },
    opacity = "1.0 override 1.0 override",
})

-- VSCode glass, done at the compositor instead of by the vscode-vibrancy
-- extension. Vibrancy bought *solid text* by patching Electron's main.js in
-- /usr/share/code as root, which meant a pkexec prompt on every VSCode and
-- extension update. Not worth it. Electron has no background-opacity knob of
-- its own (unlike Ghostty above), so the whole window fades a little here,
-- text included. Global blur (decoration.blur) fills in behind it.
hl.window_rule({
    name  = "code-glass",
    match = { class = "^([Cc]ode|code-url-handler|code-oss|[Vv][Ss][Cc]odium)$" },
    opacity = "0.92 override 0.88 override",
})

-- ── Popups & dialogs should float, not tile ──────────────────

-- Any modal dialog ("Are you sure", auth prompts, etc.)
hl.window_rule({
    name  = "float-modals",
    match = { modal = true },
    float = true,
})

-- Thunar operation dialogs (file transfer progress, replace confirms, ...)
hl.window_rule({
    name  = "float-thunar-dialogs",
    match = {
        class = "^([Tt]hunar)$",
        title = "^(File Operation Progress|Confirm to replace files|Rename .*|Create New Folder|Attention|Compressing .*|Extracting .*)$",
    },
    float = true,
})

-- Chrome/Chromium popup windows (OAuth sign-in etc. open as about:blank)
hl.window_rule({
    name  = "float-chrome-popups",
    match = {
        class         = "^([Gg]oogle-chrome|[Cc]hromium|[Bb]rave-browser)$",
        initial_title = "^(about:blank)$",
    },
    float = true,
})

-- Generic auth / sign-in windows by title
hl.window_rule({
    name  = "float-auth-popups",
    match = { title = "^(Sign [Ii]n|Log [Ii]n|Login|Authentication [Rr]equired|Confirm).*" },
    float = true,
})

-- ── 🗄️ Scratchpad terminal ───────────────────────────────────
-- Anything tagged with this app-id lands in special:magic instead of the
-- tiling layout. ghostty --class sets it; scripts/scratch-term.sh spawns it.
hl.window_rule({
    name  = "scratch-term-to-special",
    match = { class = "^(com\\.scratch\\.term)$" },
    workspace = "special:magic",
})

-- ── 🐉 Garuda tools ──────────────────────────────────────────
-- Distro settings/maintenance GUIs. These are one-off dialogs you open,
-- change a thing in, and close — tiling them shoves the actual workspace
-- around for no benefit. Class confirmed at runtime as
-- "garuda-system-maintenance"; none of these ship a StartupWMClass, so the
-- pattern covers the binary names (incl. the two without a garuda- prefix).
hl.window_rule({
    name  = "float-garuda-tools",
    match = { class = "^([Gg]aruda-.*|setup-assistant|snapper-tools)$" },
    float  = true,
    center = true,
})

-- Portal file pickers (Open/Save dialogs)
hl.window_rule({
    name  = "float-file-pickers",
    match = { class = "^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|org.freedesktop.impl.portal.desktop.kde)$" },
    float = true,
})

-- ── 🖥️ Screen sharing ────────────────────────────────────────
-- The portal's source picker had NO rule at all, so it tiled into the layout
-- the moment a call asked to share — the worst possible time to be fighting
-- the window manager. Float it, centre it, and pin it above the tiles.
hl.window_rule({
    name  = "float-share-picker",
    match = { class = "^(hyprland-share-picker|xdg-desktop-portal-hyprland)$" },
    float  = true,
    center = true,
    pin    = true,
    size   = "720 480",
})

-- Chrome's "<site> is sharing your screen" indicator bar. Floats and pins so
-- it stops stealing a tile slot mid-call.
hl.window_rule({
    name  = "float-share-indicator",
    match = { title = ".*(is sharing your screen|Share your screen|Stop sharing).*" },
    float = true,
    pin   = true,
})

-- ── 🔐 Browser popups ────────────────────────────────────────
-- Chrome opens OAuth/sign-in flows via window.open. The old rule only caught
-- an initial title of exactly "about:blank"; in practice these map with an
-- empty title, so they slipped through and tiled.
hl.window_rule({
    name  = "float-chrome-popup-blank",
    match = {
        class         = "^([Gg]oogle-chrome|[Cc]hromium|[Bb]rave-browser|[Hh]elium)$",
        initial_title = "^(|about:blank|Sign in.*|.*Google Accounts.*)$",
    },
    float = true,
})

-- Auth flows by title, matched on the initial title so the rule fires at map
-- time rather than after the page has already been slotted into the layout.
hl.window_rule({
    name  = "float-auth-popups-initial",
    match = { initial_title = "^(Sign [Ii]n|Sign [Uu]p|Log [Ii]n|Login|Authentication [Rr]equired|Authorize|OAuth|Confirm|.*Google Accounts).*" },
    float = true,
})


hl.bind("SUPER + tab", function ()
    local layouts     = { "scrolling", "dwindle", "master", "monocle" }
    if hl.plugin ~= nil and hl.plugin.hy3 ~= nil then
        table.insert(layouts, 1, "hy3")
    end
    local workspace   = hl.get_active_workspace()
	if hl.get_active_special_workspace() then
		workspace = hl.get_active_special_workspace()
	end

    local next_layout = "dwindle"

    if not workspace then
        return
    end

    for i = 1, #layouts do
        if layouts[i] == workspace.tiled_layout then
            local next_layout_idx = (i % #layouts) + 1
            next_layout = layouts[next_layout_idx]
            break
        end
    end

	if workspace.special then
		hl.workspace_rule({ workspace = tostring(workspace.name), layout = next_layout })
	else
		hl.workspace_rule({ workspace = tostring(workspace.id), layout = next_layout })
	end
end)

hl.bind("SUPER + F1", function ()
    local game_mode = (hl.get_config("animations.enabled") == false)

    if game_mode then
        hl.exec_cmd("hyprctl reload")
        return
    end
    
    hl.config({
        general = {
            gaps_in = 0, gaps_out = 0, -- Disable gaps  
            border_size = 0,
        },

        animations = {
            enabled = false, -- Disable animations
        },
        
        -- Disable blur, shadow and window rounding
        decoration = {
            shadow = { enabled = false },
            blur = { enabled = false },
            rounding = 0,
        }
    })
end)
