general {
    lock_cmd = pidof hyprlock || hyprlock       # Kilitleme komutu
    before_sleep_cmd = loginctl lock-session    # Uyku moduna girmeden önce kilitle
    after_sleep_cmd = hyprctl dispatch dpms on  # Uyanınca ekranı aç
}

listener {
    timeout = 600                                # 600 saniye = 10 dakika
    on-timeout = loginctl lock-session           # Süre dolunca ekranı kilitle
}

listener {
    timeout = 630                                # 10.5 dakika (Kilitlendikten biraz sonra)
    on-timeout = hyprctl dispatch dpms off       # Ekranı tamamen kapat (güç tasarrufu)
    on-resume = hyprctl dispatch dpms on        # Hareket edince ekranı geri aç
}
